# Copyright (c) 2024-2025 zihan wang
# SPDX-License-Identifier: Apache-2.0

"""
Procedural Robot Environment.

This module provides a custom ManagerBasedRLEnv that supports procedurally
generated robots using the metamorphosis framework.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from isaaclab.envs import ManagerBasedRLEnv

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnvCfg


class ProceduralRobotEnv(ManagerBasedRLEnv):
    """Custom environment for procedurally generated robots.
    
    This environment extends ManagerBasedRLEnv to support robots with
    heterogeneous morphologies generated by the metamorphosis framework.
    
    Key features:
    - Calls builder.modify_articulation() after scene setup to adjust
      joint limits and default positions based on morphology parameters
    - Supports non-homogeneous physics views (replicate_physics=False)
    """
    
    def __init__(self, cfg: ManagerBasedRLEnvCfg, render_mode: str | None = None, **kwargs):
        """Initialize the procedural robot environment.
        
        Args:
            cfg: The environment configuration.
            render_mode: The render mode for the environment.
            **kwargs: Additional keyword arguments.
        """
        super().__init__(cfg, render_mode, **kwargs)
        
        # After scene setup, modify articulation properties based on morphology
        # This also sets per-robot default joint positions and initial heights
        self._modify_procedural_articulations()
        
        # Set morphology parameters as observation (for heterogeneous training)
        self._set_morphology_params()
    
    def _modify_procedural_articulations(self):
        """Modify articulation properties for procedural robots.
        
        This method calls the builder's modify_articulation method to adjust
        joint limits and default positions based on the sampled morphology.
        """
        # Check if we have a robot in the scene
        if "robot" not in self.scene.articulations:
            return
        
        robot = self.scene.articulations["robot"]
        
        # Try to get the QuadrupedBuilder instance and modify articulation
        try:
            from metamorphosis.builder import QuadrupedBuilder
            
            try:
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadrupedBuilder, 'modify_articulation'):
                        QuadrupedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadrupeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try QuadWheelBuilder if available
        try:
            from metamorphosis.builder import QuadWheelBuilder
            
            try:
                builder = QuadWheelBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadWheelBuilder, 'modify_articulation'):
                        QuadWheelBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadwheel robots")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try BipedBuilder if available
        try:
            from metamorphosis.builder import BipedBuilder
            
            try:
                builder = BipedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(BipedBuilder, 'modify_articulation'):
                        BipedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural bipeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
    
    def _set_morphology_params(self):
        """Extract morphology parameters and store as normalized tensor for observations."""
        import torch
        
        # Try QuadrupedBuilder
        try:
            from metamorphosis.builder import QuadrupedBuilder
            
            try:
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    # Extract parameters: [base_length, base_width, base_height, 
                    #                      thigh_length, calf_length, thigh_radius, parallel_abduction]
                    params_list = []
                    for param in builder.params:
                        params_list.append([
                            param.base_length,
                            param.base_width,
                            param.base_height,
                            param.thigh_length,
                            param.calf_length,
                            param.thigh_radius,
                            float(param.parallel_abduction),  # bool -> float
                        ])
                    
                    params_tensor = torch.tensor(params_list, device=self.device, dtype=torch.float32)
                    
                    # Normalize to roughly [-1, 1] for better learning
                    # Using approximate ranges: base(0.5-1.0), width(0.3-0.4), height(0.15-0.25),
                    # thigh(0.2-0.8), calf(0.18-0.8), radius(0.03-0.05), parallel(0-1)
                    normalization = torch.tensor(
                        [[0.75, 0.35, 0.20, 0.50, 0.50, 0.04, 0.5]],  # mean
                        device=self.device
                    )
                    scale = torch.tensor(
                        [[0.25, 0.05, 0.05, 0.30, 0.30, 0.01, 0.5]],  # std/range
                        device=self.device
                    )
                    self.morphology_params_tensor = (params_tensor - normalization) / scale
                    self.morphology_params_dim = self.morphology_params_tensor.shape[-1]
                    
                    print(f"[INFO] Set morphology parameters for {len(builder.params)} robots")
                    print(f"       Shape: {self.morphology_params_tensor.shape}")
                    print(f"       Example env0: {self.morphology_params_tensor[0].cpu().numpy()}")
                    return
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass

        # Try BipedBuilder (procedural humanoid)
        try:
            from metamorphosis.builder import BipedBuilder

            try:
                builder = BipedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    # Extract key morphology parameters for humanoid adaptation.
                    # [torso_len, torso_width, torso_height, pelvis_height, hip_spacing,
                    #  hip_pitch_len, hip_roll_len, thigh_len, shin_len, foot_len]
                    params_list = []
                    for param in builder.params:
                        params_list.append([
                            param.torso_link_length,
                            param.torso_link_width,
                            param.torso_link_height,
                            param.pelvis_height,
                            param.hip_spacing,
                            param.hip_pitch_link_length,
                            param.hip_roll_link_length,
                            param.hip_yaw_link_length,
                            param.knee_link_length,
                            param.ankle_roll_link_length,
                        ])

                    params_tensor = torch.tensor(params_list, device=self.device, dtype=torch.float32)

                    # Approximate normalization from ProceduralBipedCfg default ranges.
                    normalization = torch.tensor(
                        [[0.13, 0.22, 0.11, 0.065, 0.20, 0.045, 0.045, 0.30, 0.31, 0.215]],
                        device=self.device,
                    )
                    scale = torch.tensor(
                        [[0.03, 0.04, 0.03, 0.015, 0.04, 0.015, 0.015, 0.08, 0.09, 0.035]],
                        device=self.device,
                    )

                    self.morphology_params_tensor = (params_tensor - normalization) / scale
                    self.morphology_params_dim = self.morphology_params_tensor.shape[-1]

                    print(f"[INFO] Set morphology parameters for {len(builder.params)} humanoids")
                    print(f"       Shape: {self.morphology_params_tensor.shape}")
                    print(f"       Example env0: {self.morphology_params_tensor[0].cpu().numpy()}")
                    return
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Fallback: set zeros if no builder found
        self.morphology_params_dim = 7
        self.morphology_params_tensor = torch.zeros(self.num_envs, self.morphology_params_dim, device=self.device)

    

