# Copyright (c) 2024-2025 zihan wang
# SPDX-License-Identifier: Apache-2.0

"""
Procedural Robot Environment.

This module provides a custom ManagerBasedRLEnv that supports procedurally
generated robots using the metamorphosis framework.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from isaaclab.envs import ManagerBasedRLEnv

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnvCfg


class ProceduralRobotEnv(ManagerBasedRLEnv):
    """Custom environment for procedurally generated robots.
    
    This environment extends ManagerBasedRLEnv to support robots with
    heterogeneous morphologies generated by the metamorphosis framework.
    
    Key features:
    - Calls builder.modify_articulation() after scene setup to adjust
      joint limits and default positions based on morphology parameters
    - Supports non-homogeneous physics views (replicate_physics=False)
    """
    
    def __init__(self, cfg: ManagerBasedRLEnvCfg, render_mode: str | None = None, **kwargs):
        """Initialize the procedural robot environment.
        
        Args:
            cfg: The environment configuration.
            render_mode: The render mode for the environment.
            **kwargs: Additional keyword arguments.
        """
        super().__init__(cfg, render_mode, **kwargs)
        
        # After scene setup, modify articulation properties based on morphology
        self._modify_procedural_articulations()
    
    def _modify_procedural_articulations(self):
        """Modify articulation properties for procedural robots.
        
        This method calls the builder's modify_articulation method to adjust
        joint limits and default positions based on the sampled morphology.
        """
        # Check if we have a robot in the scene
        if "robot" not in self.scene.articulations:
            return
        
        robot = self.scene.articulations["robot"]
        
        # Try to get the QuadrupedBuilder instance and modify articulation
        try:
            from metamorphosis.builder import QuadrupedBuilder
            
            try:
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadrupedBuilder, 'modify_articulation'):
                        QuadrupedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadrupeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try QuadWheelBuilder if available
        try:
            from metamorphosis.builder import QuadWheelBuilder
            
            try:
                builder = QuadWheelBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadWheelBuilder, 'modify_articulation'):
                        QuadWheelBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadwheel robots")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try BipedBuilder if available
        try:
            from metamorphosis.builder import BipedBuilder
            
            try:
                builder = BipedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(BipedBuilder, 'modify_articulation'):
                        BipedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural bipeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
