# Copyright (c) 2024-2025 zihan wang
# SPDX-License-Identifier: Apache-2.0

"""
Procedural Robot Environment.

This module provides a custom ManagerBasedRLEnv that supports procedurally
generated robots using the metamorphosis framework.

Supports two modes:
  1. Online procedural generation (original ProceduralQuadrupedCfg spawner)
  2. Pre-generated USD loading (PreGeneratedQuadrupedCfg spawner)
  
In both cases, morphology parameters are cached and exposed as
`self.morphology_params_tensor` for injection into observations.
"""

from __future__ import annotations

import torch
import numpy as np
from typing import TYPE_CHECKING

from isaaclab.envs import ManagerBasedRLEnv

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnvCfg


class ProceduralRobotEnv(ManagerBasedRLEnv):
    """Custom environment for procedurally generated robots.
    
    This environment extends ManagerBasedRLEnv to support robots with
    heterogeneous morphologies generated by the metamorphosis framework.
    
    Key features:
    - Calls builder.modify_articulation() after scene setup to adjust
      joint limits and default positions based on morphology parameters
    - Supports non-homogeneous physics views (replicate_physics=False)
    - Caches and normalizes morphology parameters for observation injection
    """
    
    def __init__(self, cfg: ManagerBasedRLEnvCfg, render_mode: str | None = None, **kwargs):
        """Initialize the procedural robot environment.
        
        Args:
            cfg: The environment configuration.
            render_mode: The render mode for the environment.
            **kwargs: Additional keyword arguments.
        """
        super().__init__(cfg, render_mode, **kwargs)
        
        # After scene setup, modify articulation properties based on morphology
        self._modify_procedural_articulations()
        
        # Cache morphology parameters for observation injection
        self._setup_morphology_params()
    
    def _setup_morphology_params(self):
        """Set up normalized morphology parameter tensor for observations.
        
        Attempts to retrieve morphology parameters from:
          1. PreGeneratedQuadrupedCfg spawner (if using pre-generated USDs)
          2. QuadrupedBuilder instance (if using online generation)
          3. Falls back to zeros if neither is available
        
        The parameter vector is [N, 7]:
            [base_length, base_width, base_height, thigh_length, calf_length, 
             thigh_radius, parallel_abduction]
        
        Values are normalized to roughly [-1, 1] using empirical min/max ranges.
        """
        raw_params = None
        
        # Method 1: Try to get from PreGeneratedQuadrupedCfg
        try:
            from metamorphosis.pregenerated_asset_cfg import PreGeneratedQuadrupedCfg
            robot_cfg = self.cfg.scene.robot
            if hasattr(robot_cfg, 'spawn') and isinstance(robot_cfg.spawn, PreGeneratedQuadrupedCfg):
                spawner = robot_cfg.spawn
                if hasattr(spawner, '_morphology_params') and spawner._morphology_params is not None:
                    raw_params = spawner._morphology_params  # numpy [N, 7]
                    print(f"[ProceduralRobotEnv] Got morphology params from PreGeneratedQuadrupedCfg: {raw_params.shape}")
        except ImportError:
            pass
        
        # Method 2: Try to get from QuadrupedBuilder
        if raw_params is None:
            try:
                from metamorphosis.builder import QuadrupedBuilder
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    params_list = builder.params
                    raw_params = np.array([
                        [p.base_length, p.base_width, p.base_height,
                         p.thigh_length, p.calf_length, p.thigh_radius,
                         float(p.parallel_abduction)]
                        for p in params_list
                    ], dtype=np.float32)
                    print(f"[ProceduralRobotEnv] Got morphology params from QuadrupedBuilder: {raw_params.shape}")
            except (ImportError, RuntimeError, KeyError):
                pass
        
        # Method 3: Fallback to zeros
        if raw_params is None:
            print("[ProceduralRobotEnv] No morphology params available, using zeros")
            self.morphology_params_tensor = torch.zeros(
                self.num_envs, 7, device=self.device
            )
            return
        
        # Normalize parameters to roughly [-1, 1]
        # Empirical ranges based on typical quadruped configurations
        param_min = np.array([0.3, 0.2, 0.05, 0.1, 0.1, 0.02, 0.0], dtype=np.float32)
        param_max = np.array([1.2, 0.6, 0.30, 0.8, 0.8, 0.06, 1.0], dtype=np.float32)
        param_range = param_max - param_min
        param_range[param_range < 1e-6] = 1.0  # avoid division by zero
        
        # Normalize: map [min, max] → [-1, 1]
        normalized = 2.0 * (raw_params - param_min) / param_range - 1.0
        normalized = np.clip(normalized, -2.0, 2.0)  # clip outliers
        
        self.morphology_params_tensor = torch.tensor(
            normalized, device=self.device, dtype=torch.float32
        )
        
        # Handle case where num_envs > len(raw_params) (repeating pattern)
        if self.morphology_params_tensor.shape[0] < self.num_envs:
            # Repeat to match num_envs
            repeats = (self.num_envs + self.morphology_params_tensor.shape[0] - 1) // self.morphology_params_tensor.shape[0]
            self.morphology_params_tensor = self.morphology_params_tensor.repeat(repeats, 1)[:self.num_envs]
        
        print(f"[ProceduralRobotEnv] Morphology params tensor: {self.morphology_params_tensor.shape}, "
              f"range: [{self.morphology_params_tensor.min():.2f}, {self.morphology_params_tensor.max():.2f}]")
    
    def _modify_procedural_articulations(self):
        """Modify articulation properties for procedural robots.
        
        This method calls the builder's modify_articulation method to adjust
        joint limits and default positions based on the sampled morphology.
        """
        # Check if we have a robot in the scene
        if "robot" not in self.scene.articulations:
            return
        
        robot = self.scene.articulations["robot"]
        
        # Try to get the QuadrupedBuilder instance and modify articulation
        try:
            from metamorphosis.builder import QuadrupedBuilder
            
            # Check if builder was used (by checking if instance exists)
            try:
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadrupedBuilder, 'modify_articulation'):
                        QuadrupedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadrupeds")
            except (RuntimeError, KeyError):
                # Builder not initialized, skip modification
                pass
        except ImportError:
            # metamorphosis not installed, skip
            pass
        
        # Try QuadWheelBuilder if available
        try:
            from metamorphosis.builder import QuadWheelBuilder
            
            try:
                builder = QuadWheelBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadWheelBuilder, 'modify_articulation'):
                        QuadWheelBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadwheel robots")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try BipedBuilder if available
        try:
            from metamorphosis.builder import BipedBuilder
            
            try:
                builder = BipedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(BipedBuilder, 'modify_articulation'):
                        BipedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural bipeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        