# Copyright (c) 2024-2025 zihan wang
# SPDX-License-Identifier: Apache-2.0

"""
Procedural Robot Environment.

This module provides a custom ManagerBasedRLEnv that supports procedurally
generated robots using the metamorphosis framework.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from isaaclab.envs import ManagerBasedRLEnv

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnvCfg


class ProceduralRobotEnv(ManagerBasedRLEnv):
    """Custom environment for procedurally generated robots.
    
    This environment extends ManagerBasedRLEnv to support robots with
    heterogeneous morphologies generated by the metamorphosis framework.
    
    Key features:
    - Calls builder.modify_articulation() after scene setup to adjust
      joint limits and default positions based on morphology parameters
    - Supports non-homogeneous physics views (replicate_physics=False)
    """
    
    def __init__(self, cfg: ManagerBasedRLEnvCfg, render_mode: str | None = None, **kwargs):
        """Initialize the procedural robot environment.
        
        Args:
            cfg: The environment configuration.
            render_mode: The render mode for the environment.
            **kwargs: Additional keyword arguments.
        """
        super().__init__(cfg, render_mode, **kwargs)
        
        # After scene setup, modify articulation properties based on morphology
        self._modify_procedural_articulations()
    
    def _modify_procedural_articulations(self):
        """Modify articulation properties for procedural robots.
        
        This method calls the builder's modify_articulation method to adjust
        joint limits and default positions based on the sampled morphology.
        """
        # Check if we have a robot in the scene
        if "robot" not in self.scene.articulations:
            return
        
        robot = self.scene.articulations["robot"]
        
        # Try to get the QuadrupedBuilder instance and modify articulation
        try:
            from metamorphosis.builder import QuadrupedBuilder
            
            # Check if builder was used (by checking if instance exists)
            try:
                builder = QuadrupedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadrupedBuilder, 'modify_articulation'):
                        QuadrupedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadrupeds")
            except (RuntimeError, KeyError):
                # Builder not initialized, skip modification
                pass
        except ImportError:
            # metamorphosis not installed, skip
            pass
        
        # Try QuadWheelBuilder if available
        try:
            from metamorphosis.builder import QuadWheelBuilder
            
            try:
                builder = QuadWheelBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(QuadWheelBuilder, 'modify_articulation'):
                        QuadWheelBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural quadwheel robots")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass
        
        # Try BipedBuilder if available
        try:
            from metamorphosis.builder import BipedBuilder
            
            try:
                builder = BipedBuilder.get_instance()
                if builder is not None and len(builder.params) > 0:
                    if hasattr(BipedBuilder, 'modify_articulation'):
                        BipedBuilder.modify_articulation(robot)
                        print(f"[INFO] Modified articulation for {len(builder.params)} procedural bipeds")
            except (RuntimeError, KeyError):
                pass
        except ImportError:
            pass

        # ===== General Rewards =====
        self.rewards.is_alive = None
        self.rewards.is_terminated = None
        
        # ===== Base Rewards =====
        # Tracking rewards
        self.rewards.track_lin_vel_xy_exp.weight = 2.5
        self.rewards.track_ang_vel_z_exp.weight = 0.75
        
        # Base penalties
        self.rewards.lin_vel_z_l2 = None
        self.rewards.ang_vel_xy_l2.weight = -0.1  
        self.rewards.flat_orientation_l2.weight = -3.0
        
        self.rewards.base_height_l2.weight = -2.0
        self.rewards.base_height_l2.params["target_height"] = 0.3
        self.rewards.body_lin_acc_l2 = None
        self.rewards.base_ang_vel_x_l2 = None
        
        # ===== Joint Rewards =====
        self.rewards.joint_torques_l2.weight = -2.5e-5
        self.rewards.joint_vel_l1 = None
        self.rewards.joint_vel_l2.weight = -0.01  
        self.rewards.joint_acc_l2.weight = -2.0e-7  
        self.rewards.joint_deviation_l1 = None
        self.rewards.joint_pos_limits.weight = -1.0
        self.rewards.joint_vel_limits = None
        self.rewards.applied_torque_limits = None
        self.rewards.joint_power = None
        
        # Action penalties 
        self.rewards.action_rate_l2.weight = -0.01  
        self.rewards.action_l2 = None
        
        # ===== Contact Rewards =====
        # Undesired contacts 
        self.rewards.undesired_contacts.weight = -1.0
        self.rewards.undesired_contacts.params["sensor_cfg"].body_names = ".*_(calf|thigh)"
        self.rewards.desired_contacts = None
        self.rewards.contact_forces = None
        
        # Feet rewards - 关键：鼓励正常步态
        self.rewards.feet_air_time.weight = 0.5  # 大幅增加权重，鼓励足够的腾空时间
        self.rewards.feet_air_time.params["sensor_cfg"].body_names = ".*_foot"
        self.rewards.feet_air_time.params["threshold"] = 0.4  # 设置最小腾空时间阈值
        self.rewards.feet_height = None
        self.rewards.feet_slide.weight = -0.1  # 启用，惩罚脚部滑动
        
        # ===== Other/Custom Rewards =====
        # Standing still
        self.rewards.stand_till.weight = -0.5  # 减小惩罚，避免在低速时过度惩罚
        self.rewards.stand_till.params["command_name"] = "base_velocity"
        
        # Body orientation
        self.rewards.body_roll_l2.weight = -5.0
        self.rewards.body_pitch_l2 = None
        
        # Diagonal gait symmetry (Trot Gait: FL+RR, FR+RL)
        self.rewards.joint_symmetry_l2.weight = -0.1
        self.rewards.joint_symmetry_l2.params["mirror_joints"] = [
            ["FL_.*_joint", "RR_.*_joint"],  # 前左 + 后右 (对角线1)
            ["FR_.*_joint", "RL_.*_joint"],  # 前右 + 后左 (对角线2)
        ]
        self.rewards.action_symmetry_l2.weight = -0.05
        self.rewards.action_symmetry_l2.params["mirror_joints"] = [
            ["FL_.*_joint", "RR_.*_joint"],  # 前左 + 后右 (对角线1)
            ["FR_.*_joint", "RL_.*_joint"],  # 前右 + 后左 (对角线2)
        ]
        
        # ===== Handstand/Footstand Rewards =====
        self.rewards.handstand_feet_height_exp = None
        self.rewards.handstand_feet_on_air = None
        self.rewards.handstand_feet_air_time = None
        self.rewards.handstand_orientation_l2 = None
        